import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f4f1ea',
  },
  page: {
    width: '100%',
    maxWidth: 1120,
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 40,
    gap: 16,
  },
  hero: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e7ddd0',
    borderRadius: 28,
    padding: 22,
  },
  kicker: {
    color: '#8b6c52',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  title: {
    color: '#181511',
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '900',
    marginBottom: 10,
    maxWidth: 780,
  },
  subtitle: {
    color: '#62584f',
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 740,
  },
  meta: {
    color: '#8b8178',
    marginTop: 12,
    fontSize: 12,
  },
  heroButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  columns: {
    gap: 16,
  },
  columnsWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  column: {
    flex: 1,
    minWidth: 320,
  },
  leftColumn: {
    flex: 1.05,
  },
  rightColumn: {
    flex: 0.95,
  },
  card: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e6dbcc',
    borderRadius: 24,
    padding: 18,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  cardHeaderCopy: {
    flex: 1,
  },
  cardTitle: {
    color: '#181511',
    fontSize: 18,
    fontWeight: '900',
  },
  cardSubtitle: {
    color: '#6f655d',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  field: {
    marginBottom: 12,
  },
  label: {
    color: '#7a6f67',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#dcd2c4',
    backgroundColor: '#fffdf9',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#181511',
    fontSize: 15,
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#181511',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonSecondary: {
    backgroundColor: '#ece6dd',
  },
  buttonDanger: {
    backgroundColor: '#8b3d2c',
  },
  buttonGhost: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#d8ccbe',
  },
  buttonPressed: {
    opacity: 0.82,
  },
  buttonText: {
    color: '#fffaf4',
    fontWeight: '800',
    fontSize: 13,
  },
  buttonTextDark: {
    color: '#1f1a17',
  },
  buttonTextLight: {
    color: '#fffaf4',
  },
  pager: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 12,
  },
  pagerInfo: {
    flex: 1,
    alignItems: 'center',
  },
  pagerTitle: {
    color: '#1f1a17',
    fontSize: 13,
    fontWeight: '900',
  },
  pagerSub: {
    color: '#6d625a',
    fontSize: 12,
    marginTop: 2,
  },
  error: {
    color: '#8b3d2c',
    fontWeight: '800',
    marginBottom: 12,
  },
  list: {
    gap: 10,
  },
  listItem: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
  },
  questionItem: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
  },
  listItemActive: {
    backgroundColor: '#f8f0e7',
    borderColor: '#1f1a17',
  },
  questionItemActive: {
    backgroundColor: '#f8f0e7',
    borderColor: '#1f1a17',
  },
  listItemPressed: {
    opacity: 0.86,
  },
  listItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  listItemCopy: {
    flex: 1,
  },
  listItemTitle: {
    color: '#181511',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '800',
  },
  listItemMeta: {
    color: '#746a61',
    fontSize: 12,
    marginTop: 4,
  },
  listItemDescription: {
    color: '#534a43',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#ece2d4',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    color: '#6d4b32',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailBox: {
    marginTop: 10,
    backgroundColor: '#f8f5ef',
    borderWidth: 1,
    borderColor: '#e4d9ca',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  detailLabel: {
    color: '#7d7268',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 8,
  },
  detailValue: {
    color: '#181511',
    fontSize: 13,
    lineHeight: 18,
  },
  questionBox: {
    marginTop: 10,
    backgroundColor: '#f8f5ef',
    borderWidth: 1,
    borderColor: '#e4d9ca',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  questionTitle: {
    color: '#7d7268',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  questionText: {
    color: '#181511',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  phraseBox: {
    marginTop: 10,
    backgroundColor: '#f8f5ef',
    borderWidth: 1,
    borderColor: '#e4d9ca',
    borderRadius: 20,
    padding: 14,
    gap: 10,
  },
  phraseTitle: {
    color: '#7d7268',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  phraseRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  phraseWord: {
    backgroundColor: '#181511',
    color: '#fffaf4',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
    fontWeight: '900',
  },
  phraseBlank: {
    minWidth: 54,
    minHeight: 18,
    borderBottomWidth: 2,
    borderBottomColor: '#c8b9ab',
    marginHorizontal: 2,
  },
  bankBox: {
    marginTop: 12,
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e6dbcc',
    borderRadius: 20,
    padding: 14,
    gap: 12,
  },
  bankHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'flex-start',
  },
  bankTitle: {
    color: '#181511',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  bankSubtitle: {
    color: '#6f655d',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  bankGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  bankItem: {
    backgroundColor: '#f6f1e7',
    borderWidth: 1,
    borderColor: '#dfd2c1',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 112,
  },
  bankItemSelected: {
    backgroundColor: '#181511',
    borderColor: '#181511',
  },
  bankItemLocked: {
    opacity: 0.42,
  },
  bankItemText: {
    color: '#181511',
    fontSize: 13,
    fontWeight: '900',
  },
  bankItemTextSelected: {
    color: '#fffaf4',
  },
  bankItemTextLocked: {
    color: '#8e7f73',
  },
  bankItemMeta: {
    color: '#7f7167',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 4,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  bankItemMetaSelected: {
    color: '#d8c3b0',
  },
  liveNotice: {
    color: '#0f6a3c',
    fontWeight: '800',
    marginBottom: 12,
  },
  responseFeedback: {
    fontWeight: '900',
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    overflow: 'hidden',
  },
  responseFeedbackPositive: {
    color: '#0f6a3c',
    backgroundColor: '#e6f5ec',
  },
  responseFeedbackNegative: {
    color: '#8b3d2c',
    backgroundColor: '#f8e7e2',
  },
  optionSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  resultSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 8,
  },
  resultSummaryCard: {
    flexGrow: 1,
    flexBasis: 140,
    backgroundColor: '#f8f5ef',
    borderWidth: 1,
    borderColor: '#e4d9ca',
    borderRadius: 18,
    padding: 14,
    gap: 4,
  },
  resultSummarySeat: {
    color: '#7d7268',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  resultSummaryScore: {
    color: '#181511',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
  },
  resultSummaryMeta: {
    color: '#63584f',
    fontSize: 12,
    lineHeight: 17,
  },
  feedbackSection: {
    marginTop: 16,
    gap: 12,
  },
  feedbackCard: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
    gap: 12,
  },
  feedbackCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  feedbackAnswerGroup: {
    gap: 6,
  },
  feedbackLabel: {
    color: '#7d7268',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  feedbackAnswerList: {
    gap: 10,
  },
  feedbackAnswerRow: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  feedbackAnswerRowPositive: {
    backgroundColor: '#e6f5ec',
    borderColor: '#b8e1c8',
  },
  feedbackAnswerRowNegative: {
    backgroundColor: '#f8e7e2',
    borderColor: '#ebc4b8',
  },
  feedbackAnswerRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  feedbackAnswerSeat: {
    color: '#181511',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  feedbackAnswerState: {
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  feedbackAnswerStatePositive: {
    color: '#0f6a3c',
  },
  feedbackAnswerStateNegative: {
    color: '#8b3d2c',
  },
  feedbackAnswerText: {
    color: '#181511',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  answerChip: {
    backgroundColor: '#1f1a17',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  answerChipText: {
    color: '#fffaf4',
    fontSize: 12,
    fontWeight: '800',
  },
  optionPick: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e5d8cb',
    borderRadius: 18,
    padding: 14,
  },
  optionPickActive: {
    backgroundColor: '#f7efe4',
    borderColor: '#1f1a17',
  },
  sessionActions: {
    marginTop: 14,
    gap: 10,
  },
  feedBox: {
    marginTop: 16,
    backgroundColor: '#f8f5ef',
    borderWidth: 1,
    borderColor: '#e4d9ca',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  feedItem: {
    color: '#4f463f',
    fontSize: 13,
    lineHeight: 18,
  },
  quizHeaderBox: {
    backgroundColor: '#f8f5ef',
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
  },
  quizHeaderTitle: {
    color: '#181511',
    fontSize: 16,
    fontWeight: '900',
  },
  quizHeaderSub: {
    color: '#6f6258',
    fontSize: 12,
    marginTop: 4,
  },
  toggle: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#d8ccbe',
    backgroundColor: '#f6f1e7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
  },
  toggleActive: {
    borderColor: '#181511',
    backgroundColor: '#181511',
  },
  toggleText: {
    color: '#181511',
    fontWeight: '800',
    fontSize: 12,
  },
  toggleTextActive: {
    color: '#fffaf4',
  },
  optionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  optionsTitle: {
    color: '#181511',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  optionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 10,
    alignItems: 'flex-end',
  },
  optionField: {
    flex: 1,
    minWidth: 120,
  },
  optionLabelRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  optionLabelChip: {
    borderWidth: 1,
    borderColor: '#d8ccbe',
    backgroundColor: '#f6f1e7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  optionLabelChipActive: {
    borderColor: '#181511',
    backgroundColor: '#181511',
  },
  optionLabelText: {
    color: '#181511',
    fontWeight: '800',
    fontSize: 12,
  },
  optionLabelTextActive: {
    color: '#fffaf4',
  },
  optionRemove: {
    alignSelf: 'flex-end',
  },
  optionChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  optionWord: {
    color: '#181511',
    fontSize: 13,
    fontWeight: '700',
  },
  emptyState: {
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#e6dbcc',
    borderRadius: 18,
    padding: 20,
  },
  emptyStateTitle: {
    color: '#181511',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 6,
  },
  emptyStateBody: {
    color: '#665c54',
    lineHeight: 20,
  },
  note: {
    color: '#4f463f',
    lineHeight: 20,
    marginBottom: 8,
  },
  footer: {
    marginTop: 8,
    paddingVertical: 8,
  },
  footerText: {
    color: '#71655c',
    fontSize: 12,
  },
});
